#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: assure dnsmasq installed
  apt: pkg=dnsmasq state=present

- name: remove default config file loading
  lineinfile:
    dest=/etc/default/dnsmasq
    regexp='^CONFIG_DIR='
    state=absent
  notify:
    - restart dnsmasq

- name: setup network interfaces
  template: src=Debian/interfaces.j2 dest=/etc/network/interfaces mode=0644
  notify:
    - reboot server
  when: dnsmasq_dhcp_networks|length > 0

- name: install syslinux
  apt: pkg=syslinux state=present
  when: dnsmasq_enable_tftp
