#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: assure boot image media directory exists
  file: dest="{{ dnsmasq_tftp_images_dir }}" state=directory recurse=yes mode=0755
  when: dnsmasq_enable_tftp

- name: assure mount point exists for mounting Installer ISO
  file: dest="/tmp/esxi_iso" state=directory mode=0755
  when: dnsmasq_enable_tftp

- name: check for existing boot.cfg
  stat:
    path: "{{ dnsmasq_tftp_images_dir }}/boot.cfg"
    get_checksum: no
    get_md5: no
  register: bootcfg
  when: dnsmasq_enable_tftp

- name: mount installer ISO
  mount:
    name: "{{ esxi_tftp_iso_mountpoint }}"
    src: "{{ esxi_tftp_iso }}"
    fstype: auto
    opts: "ro"
    state: mounted
  when: dnsmasq_enable_tftp and not bootcfg.stat.exists

- name: copy boot media
  command: "cp -r {{ esxi_tftp_iso_mountpoint }}/. {{ dnsmasq_tftp_images_dir }}/."
  when: dnsmasq_enable_tftp and not bootcfg.stat.exists

- name: unmount installer ISO
  mount:
    name: "{{ esxi_tftp_iso_mountpoint }}"
    src: "{{ esxi_tftp_iso }}"
    fstype: auto
    opts: "ro"
    state: unmounted
  when: dnsmasq_enable_tftp and not bootcfg.stat.exists

- name: fixup boot.cfg
  command: 'sudo sed -e "s#/##g" -e "3s#^#prefix=images/ESXi-{{ esxi_tftp_esxi_version }}/\n#" -i.bak boot.cfg'
  args:
    creates: "{{ dnsmasq_tftp_images_dir }}/boot.cfg.bak"
    chdir: "{{ dnsmasq_tftp_images_dir }}"
  when: dnsmasq_enable_tftp

- name: create kickstart configurations directory
  file: dest="{{ dnsmasq_tftp_kickstart_dir }}" state=directory mode=0755
  when: dnsmasq_enable_tftp

- name: create kickstart file
  template:
    src: "{{ dnsmasq_tftp_kickstart_template }}"
    dest: "{{ dnsmasq_tftp_kickstart_dir }}/{{ dnsmasq_tftp_kickstart_file }}"

    mode: 0644
  when: dnsmasq_enable_tftp
