#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: restart systemd-resolved
  service: name=systemd-resolved state=restarted

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: enable webroot
  command: "a2ensite tftp"

- name: restart web server
  service: name=apache2 state=restarted

- name: restart systemd-networkd
  service: name=systemd-networkd state=restarted

- name: reboot server
  command: shutdown -r now "Ansible updates triggered reboot"
  async: 0
  poll: 0
  ignore_errors: true
  notify:
    - wait for server

- name: wait for server
  sudo: false
  local_action:
    wait_for
    host={{ inventory_hostname }}
    port=22
    delay=30
    timeout=300
